spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apply_work?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mvc:
    static-path-pattern: classpath:/static/**
mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.example.demo.model
# 打印sql
logging:
  level:
    com.example.demo.mapper: debug
#springfox.documentation.swagger.v2.path: /api-docs
